apiVersion: v1
kind: ConfigMap
metadata:
  name: template-cm
  namespace: weather-bot
data:
  template.txt: |
    ğŸ”¥ <b>SHIT!</b>

    â„¹ï¸ PM 2.5: {{ .PM25 }}

    â„¹ï¸ PM 10: {{ .PM10 }}

    ğŸ’¬ URL: {{ .URL }}

    BLABLABLA.